---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ec2_region: us-west-2
    ec2_image: ami-0c55b159cbfafe1f0
    ec2_instance_type: t2.micro
    ec2_keypair: example-keypair
    ec2_security_groups: [example-sg]
    ec2_volume_size: 20

  tasks:
    # Launch an EC2 instance
    - name: Launch EC2 instance
      ec2:
        region: "{{ ec2_region }}"
        image: "{{ ec2_image }}"
        instance_type: "{{ ec2_instance_type }}"
        key_name: "{{ ec2_keypair }}"
        security_group: "{{ ec2_security_groups }}"
        count: 1
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ ec2_volume_size }}"
        assign_public_ip: yes
      register: ec2

    # Add the new instance to an Ansible group
    - name: Add new instance to Ansible group
      add_host:
        name: "{{ ec2.instances[0].public_ip }}"
        groups: ec2

- hosts: ec2
  remote_user: ec2-user
  become: yes

  tasks:
    # Install packages
    - name: Install packages
      yum:
        name: ["httpd", "php"]
        state: latest

    # Configure Apache
    - name: Configure Apache
      template:
        src: templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Apache

    # Configure PHP
    - name: Configure PHP
      template:
        src: templates/php.ini.j2
        dest: /etc/php.ini
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Apache

  handlers:
    # Restart Apache
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
